server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    #表示是否将自己注册进注册中心中，默认true
    register-with-eureka: false
    #是否从注册中心抓取已有的注册信息，默认true，单点无所谓，集群必须设置
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: order
    #访问路径显示ip地址
    prefer-ip-address: true
    #客户端向服务端发送心跳的时间间隔，s，默认30s
    lease-renewal-interval-in-seconds: 1
    #服务端在收到最后一次心跳后等待时间上线，s，默认90s，超时剔除服务
    lease-expiration-duration-in-seconds: 2