server:
  port: 8999
spring:
  application:
    name: cloud-common-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 # nacos\u6CE8\u518C\u5730\u5740
management:
  endpoints:
    web:
      exposure:
        include: '*'